apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: vs-ingresslink2
  namespace: nginx-ingress
spec:
  virtualServerAddress: "10.0.2.101"
  iRules:
    - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress
